version: '3'

services:
  transactional:
    image: postgres:12
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./data/dvdrental.sql:/docker-entrypoint-initdb.d/dvdrental.sql
    ports:
      - 5432:5432

  analytics:
    image: postgres:12
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5440:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
    depends_on:
      - transactional

  scripts:
    image: ubuntu:latest
    volumes:
      - ./scripts/extract_and_load.sh:/extract_and_load.sh
    command: bash -c "chmod +x /extract_and_load.sh && /extract_and_load.sh"
    depends_on:
      - transactional
      - analytics

volumes:
    postgres: